/* src/config.h.  Generated by configure.  */
/*------------------------------------------------------------------------*/
/**
 * @file	config.h
 * @brief   コンフィグ設定
 *
 * @author  M.Nukui
 * @date	2005-04-30
 *
 * Copyright (C) 2005 M.Nukui All rights reserved.
 */


#ifndef	CONFIG_H
#define	CONFIG_H


/* マクロ定義 */
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1

#define HAVE_LIBICONV 1
#define HAVE_DLOPEN 1

#define __PLATFORM__ "darwin"
#define __DYLIBSUFFIX__ ".dylib"

/* #undef __IPOD__ */


#endif /* CONFIG_H */
