name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        ./configure --enable-contrib
    - name: build
      run: |
        make
    - name: run tests
      run: |
        make test
    - name: archive
      run: |
        make tgz
    - uses: actions/upload-artifact@v2
      with:
        name: NEWT0 ${{matrix.os}}
        path: build/NEWT0_*.tgz
